### ISSUE TITLE
New Feature: Support for TOML Configuration File in Home Directory

### ISSUE THREAD

**Issue by MadhurSaluja** [tasbi03/ReadCraft#11]
## Issue Description:
Users would like the ability to specify options for the tool using a TOML-formatted configuration file located in their home directory, eliminating the need to pass options via command-line arguments for every execution.

For example, a user could create a file named ~/.your-toolname-config.toml containing:
```
toml
Copy code
model = "gpt-4o"
api_key = "sk-...."
# etc...
```
When running the tool, it will automatically search for this configuration file in the home directory and use the specified values as defaults. If command-line arguments are provided, they will override the values from the config file.

## Requirements:
1. The tool should search for a TOML "dotfile" (e.g., .your-toolname-config.toml) in the user's home directory containing default options in TOML format.
2. If the file is missing, the tool should continue with default or command-line-provided values.
3. If the TOML file exists but contains invalid TOML, the tool should exit with an appropriate error message.
4. The tool should prioritize command-line arguments over values in the configuration file if both are provided.
5. Any unknown or unrecognized options in the config file should be ignored by the tool.

**Comment by tasbi03** [comment]
Feature tested succeessfully and PR merged
