### ISSUE TITLE
Add Timeout for API Requests

### ISSUE THREAD

**Issue by MadhurSaluja** [tasbi03/ReadCraft#2]
The API request lacks a timeout, causing the script to hang if the API doesn’t respond. Add a timeout (e.g., timeout=10) to prevent this, and handle errors with an informative message.

**Comment by tasbi03** [comment]
Added a timeout parameter to the requests.post() call, for example, requests.post(..., timeout=10), which will limit how long the script waits for a response from the API. Additionally, handle timeout errors gracefully and provide the user with an informative error message explaining the issue.

**Comment by tasbi03** [comment]
fixed this issue with the first issue :Added a timeout parameter to the requests.post() call, for example, requests.post(..., timeout=10), which will limit how long the script waits for a response from the API. Additionally, handle timeout errors gracefully and provide the user with an informative error message explaining the issue.
